<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Nodes [

<!ENTITY % NameValue "CDATA">
<!ENTITY % PropType "(I|S|D|L|H|B)">
<!ENTITY % VersionValue "CDATA">

<!ELEMENT Prp (#PCDATA)>
<!ELEMENT Node (Node|Prp)*>
<!ELEMENT Nodes (Node)+>

<!ATTLIST Nodes version CDATA "1">

<!ATTLIST Node name CDATA #REQUIRED>

<!ATTLIST Prp name CDATA #REQUIRED>
<!ATTLIST Prp type CDATA #REQUIRED>
<!ATTLIST Prp value CDATA #REQUIRED>
]>
<Nodes version="1">
	<Node name="root">
		<Node name="classes">
			<Node name="class0">
				<Node name="fields">
					<Node name="field0">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Financial"/>
						<Prp name="name" type="S" value="DeliveryType"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field1">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Buy"/>
						<Prp name="name" type="S" value="BuySell"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field10">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="EUR"/>
						<Prp name="name" type="S" value="Currency"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field11">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Viz"/>
						<Prp name="name" type="S" value="CurrencySource"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field12">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Company first"/>
						<Prp name="name" type="S" value="Broker"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field13">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="1"/>
						<Prp name="name" type="S" value="BrokerFee"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field14">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="EUR"/>
						<Prp name="name" type="S" value="BrokerFeeCurrency"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field15">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Electronic"/>
						<Prp name="name" type="S" value="Clearing"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field16">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="0"/>
						<Prp name="name" type="S" value="ClearingFee"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field17">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="EUR"/>
						<Prp name="name" type="S" value="ClearingFeeCurrency"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field18">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="0"/>
						<Prp name="name" type="S" value="CommissionFee"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field19">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="EUR"/>
						<Prp name="name" type="S" value="CommissionFeeCurrency"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field2">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Company first"/>
						<Prp name="name" type="S" value="Portfolio"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field20">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="0"/>
						<Prp name="name" type="S" value="TradingFee"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field21">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="EUR"/>
						<Prp name="name" type="S" value="TradingFeeCurrency"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field22">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Vizard"/>
						<Prp name="name" type="S" value="Trader"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field23">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Active"/>
						<Prp name="name" type="S" value="Status"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field24">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Electricity-Future"/>
						<Prp name="name" type="S" value="Comment"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field3">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Second company"/>
						<Prp name="name" type="S" value="CounterpartyPortfolio"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field4">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Nord Pool"/>
						<Prp name="name" type="S" value="ExecutionVenue"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field5">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="NordPool System Price"/>
						<Prp name="name" type="S" value="PriceBasis"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field6">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="M05-13"/>
						<Prp name="name" type="S" value="Period"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field7">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="Base (System)"/>
						<Prp name="name" type="S" value="LoadProfile"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field8">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="963"/>
						<Prp name="name" type="S" value="Quantity"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
					<Node name="field9">
						<Prp name="checked" type="B" value="-1"/>
						<Prp name="membervalue" type="S" value="230"/>
						<Prp name="name" type="S" value="Price"/>
						<Prp name="valuetype" type="I" value="8"/>
					</Node>
				</Node>
				<Node name="methods"/>
				<Prp name="name" type="S" value="MyClass4"/>
			</Node>
		</Node>
		<Node name="data"/>
	</Node>
</Nodes>